### PR TITLE
Math Magicians React App Setup 

### PR DESCRIPTION
**Pull request by MarcoDDM**
### Description:

This pull request sets up the development environment for the Math Magicians React application. The project is the first of a series of projects that will lead to the final application. This pull request includes the following changes:

- Environment and tools are set up for React application development
- Create React App is used to create the React application
- The application runs without errors in the browser

**Checklist:**

 - Linter errors are fixed and no new errors are introduced
 - Gitflow is followed correctly
 - Documentation is clear and professional
 - Best practices for JavaScript are followed
 - Node.js is installed on the machine
 - Create React App is used to create the React application
 - The application runs without errors in the browser

Thank you for reviewing this pull request.

### CODE REVIEW

**Review by rotimiazeez — COMMENTED** [review]
# Hi @MarcoDDM , 

### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that does not have a descriptive README file. Kindly ensure you have a README file that follows this [template](https://github.com/microverseinc/readme-template) and complete all the necessary sections. 😉 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by Ismailco — COMMENTED** [review]
Hi @MarcoDDM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has professional documentation however you should only include the `Live demo` link in your README if your website is deployed. kindly consider removing the live demo section altogether.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by MarcoDDM** [comment]
> Hi @MarcoDDM,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that has professional documentation however you should only include the `Live demo` link in your README if your website is deployed. kindly consider removing the live demo section altogether.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers, and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Hello @Ismailco, I decide to leave that with the "No deployed yet" legend, because another code reviewer ask me not to remove anything on the readme, just the optional. So what should I do? Because one say something and other ask me the contrary

**Comment by Ismailco** [comment]
@MarcoDDM, for the README you should include all the sections, the only change is that if the project is deployed you should keep the `Live demo` section however if your project is not deployed yet or isn't a web app you must remove the `Live demo` section

**Review by levy002 — APPROVED** [review]
### Hello @MarcoDDM 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Status: APPROVED :fire:  :fire: 

## Highlights
- No linter errors :heavy_check_mark: 
- App is running well as expected :heavy_check_mark: 
- Well-detailed PR summary :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
